.TH "master Directory Reference" 3 "Thu May 18 2023" "Master-car" \" -*- nroff -*-
.ad l
.nh
.SH NAME
master Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmaster\&.ino\fP"
.br
.RI "This is what sent instructens to the car from the user gestures\&. This code is inspried by: A library for SeeedStudio Grove FM (Website: www\&.seeed\&.cc) by Steve Chang and Grove - Serial Bluetooth v3\&.0 examples (website: https://wiki.seeedstudio.com/Grove-Serial_Bluetooth_v3.0/) "
.in -1c
