.TH "slave Directory Reference" 3 "Wed May 31 2023" "Mini-Project-FPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
slave Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBslave\&.ino\fP"
.br
.RI "This is what control the car and recive the data from the glove\&. This code is inspried by: 
.br
 "
.in -1c
