.TH "slave/slave.ino" 3 "Wed May 31 2023" "Mini-Project-FPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
slave/slave.ino \- This is what control the car and recive the data from the glove\&. This code is inspried by: 
.br
  

.SH SYNOPSIS
.br
.PP
\fC#include <SoftwareSerial\&.h>\fP
.br
\fC#include <Servo\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRxD\fP   2"
.br
.ti -1c
.RI "#define \fBTxD\fP   3"
.br
.ti -1c
.RI "#define \fBA1\fP   3"
.br
.ti -1c
.RI "#define \fBA2\fP   5"
.br
.ti -1c
.RI "#define \fBB1\fP   6"
.br
.ti -1c
.RI "#define \fBB2\fP   9"
.br
.ti -1c
.RI "#define \fBA3\fP   11"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "SoftwareSerial \fBblueToothSerial\fP (\fBRxD\fP, \fBTxD\fP)"
.br
.ti -1c
.RI "void \fBsetup\fP ()"
.br
.RI "This is the setup function that is run when the board is started and it setup the outputs,input and create a connection to the master bord\&. "
.ti -1c
.RI "void \fBloop\fP ()"
.br
.RI "This is the function that update the bluetooth data and controlls the car\&. "
.ti -1c
.RI "void \fBclacDistiance\fP ()"
.br
.RI "Take the duration form the distance sensor and calculate teh distances\&. "
.ti -1c
.RI "void \fBupdateDistanceDisplay\fP ()"
.br
.RI "Take the distance from the distance sensor and update the 4 leds to show the distance\&. "
.ti -1c
.RI "void \fBrecieveBluetoothData\fP ()"
.br
.RI "recieve data from the \fBmaster\&.ino\fP bord with bluetooth\&. The data is then read and turn and forward values is calulated "
.ti -1c
.RI "void \fBturnControl\fP ()"
.br
.RI "turns the car according to the turn variable by using the servo motor "
.ti -1c
.RI "void \fBfeedForwardControl\fP ()"
.br
.RI "Controll the motors that makes the car move arrcording to the forward variable\&. "
.ti -1c
.RI "void \fBsetupBlueToothConnection\fP ()"
.br
.RI "inspried by the example code called:Master_button setup code website: https://wiki.seeedstudio.com/Grove-Serial_Bluetooth_v3.0/ It initilizing bluetooth connction "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "double \fBforward\fP = 0"
.br
.ti -1c
.RI "double \fBturn\fP = 0"
.br
.ti -1c
.RI "double \fBmin\fP = 2"
.br
.ti -1c
.RI "Servo \fBaxisServo\fP"
.br
.ti -1c
.RI "const unsigned int \fBMAX_MESSAGE_LENGTH\fP = 12"
.br
.ti -1c
.RI "const int \fBtrig\fP = 13"
.br
.ti -1c
.RI "const int \fBecho\fP = 12"
.br
.ti -1c
.RI "const int \fBLED1\fP = 10"
.br
.ti -1c
.RI "const int \fBLED2\fP = 8"
.br
.ti -1c
.RI "const int \fBLED3\fP = 7"
.br
.ti -1c
.RI "const int \fBLED4\fP = 4"
.br
.ti -1c
.RI "int \fBduration\fP = 0"
.br
.ti -1c
.RI "int \fBdistance\fP = 0"
.br
.ti -1c
.RI "int \fBdistances\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is what control the car and recive the data from the glove\&. This code is inspried by: 
.br
 


.IP "\(bu" 2
Grove - Serial Bluetooth v3\&.0 examples button (website: https://wiki.seeedstudio.com/Grove-Serial_Bluetooth_v3.0/)
.IP "\(bu" 2
Servo Motor Basics with Arduino: https://docs.arduino.cc/learn/electronics/servo-motors
.IP "\(bu" 2
L9110S H-bridge Dual DC Stepper Motor Driver Controller: https://arduinotech.dk/shop/l9110s-h-bridge-dual-dc-stepper-motor-driver-controller/ 
.PP

.PP
Definition in file \fBslave\&.ino\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define A1   3"
pin for Motor A 
.PP
Definition at line \fB18\fP of file \fBslave\&.ino\fP\&.
.SS "#define A2   5"
pin for Motor A 
.PP
Definition at line \fB19\fP of file \fBslave\&.ino\fP\&.
.SS "#define A3   11"
pin for controlling the servo 
.PP
Definition at line \fB24\fP of file \fBslave\&.ino\fP\&.
.SS "#define B1   6"
pin for Motor B 
.PP
Definition at line \fB21\fP of file \fBslave\&.ino\fP\&.
.SS "#define B2   9"
pin for Motor B 
.PP
Definition at line \fB22\fP of file \fBslave\&.ino\fP\&.
.SS "#define RxD   2"
pin for the bluetooth component 
.PP
Definition at line \fB13\fP of file \fBslave\&.ino\fP\&.
.SS "#define TxD   3"
pin for the bluetooth component 
.PP
Definition at line \fB14\fP of file \fBslave\&.ino\fP\&.
.SH "Function Documentation"
.PP 
.SS "SoftwareSerial blueToothSerial (\fBRxD\fP, \fBTxD\fP)"
create the the softwareSerial 
.SS "void clacDistiance ()"

.PP
Take the duration form the distance sensor and calculate teh distances\&. 
.PP
Definition at line \fB100\fP of file \fBslave\&.ino\fP\&.
.SS "void feedForwardControl ()"

.PP
Controll the motors that makes the car move arrcording to the forward variable\&. if the forward is bigger then the minimum value for forward (min) then the car can move
.PP
if foward is postive the car move forward else it move backwards
.PP
if the values of foward is less the car dont move it wheels\&.
.PP
Definition at line \fB196\fP of file \fBslave\&.ino\fP\&.
.SS "void loop ()"

.PP
This is the function that update the bluetooth data and controlls the car\&. 
.PP
Definition at line \fB86\fP of file \fBslave\&.ino\fP\&.
.SS "void recieveBluetoothData ()"

.PP
recieve data from the \fBmaster\&.ino\fP bord with bluetooth\&. The data is then read and turn and forward values is calulated have a static char array with a length of MAX_MESSAGE_LENGTH
.PP
read every symbol of the message
.PP
If full message received
.PP
read the message and save it in two strings
.PP
converting the strings to doubles and calculate the forward and turn values
.PP
Add null character to string
.PP
Definition at line \fB129\fP of file \fBslave\&.ino\fP\&.
.SS "void setup ()"

.PP
This is the setup function that is run when the board is started and it setup the outputs,input and create a connection to the master bord\&. 
.PP
Definition at line \fB62\fP of file \fBslave\&.ino\fP\&.
.SS "void setupBlueToothConnection ()"

.PP
inspried by the example code called:Master_button setup code website: https://wiki.seeedstudio.com/Grove-Serial_Bluetooth_v3.0/ It initilizing bluetooth connction 
.PP
Definition at line \fB225\fP of file \fBslave\&.ino\fP\&.
.SS "void turnControl ()"

.PP
turns the car according to the turn variable by using the servo motor 
.PP
Definition at line \fB188\fP of file \fBslave\&.ino\fP\&.
.SS "void updateDistanceDisplay ()"

.PP
Take the distance from the distance sensor and update the 4 leds to show the distance\&. 
.PP
Definition at line \fB114\fP of file \fBslave\&.ino\fP\&.
.SH "Variable Documentation"
.PP 
.SS "Servo axisServo"
Instance of the Servo that controll the front of the car 
.PP
Definition at line \fB31\fP of file \fBslave\&.ino\fP\&.
.SS "int distance = 0"
The distance from the distance sensor 
.PP
Definition at line \fB52\fP of file \fBslave\&.ino\fP\&.
.SS "int distances"

.PP
Definition at line \fB54\fP of file \fBslave\&.ino\fP\&.
.SS "int duration = 0"
The duration with the distance sensor 
.PP
Definition at line \fB50\fP of file \fBslave\&.ino\fP\&.
.SS "const int echo = 12"
pin for the echo from the distance sensor 
.PP
Definition at line \fB40\fP of file \fBslave\&.ino\fP\&.
.SS "double forward = 0"
The value that controll the forward momententiom\&. It controll the if it should move forward, backwards or stand still 
.PP
Definition at line \fB27\fP of file \fBslave\&.ino\fP\&.
.SS "const int LED1 = 10"
pin for led 1 
.PP
Definition at line \fB42\fP of file \fBslave\&.ino\fP\&.
.SS "const int LED2 = 8"
pin for led 2 
.PP
Definition at line \fB44\fP of file \fBslave\&.ino\fP\&.
.SS "const int LED3 = 7"
pin for led 3 
.PP
Definition at line \fB46\fP of file \fBslave\&.ino\fP\&.
.SS "const int LED4 = 4"
pin for led 4 
.PP
Definition at line \fB48\fP of file \fBslave\&.ino\fP\&.
.SS "const unsigned int MAX_MESSAGE_LENGTH = 12"
The max length of chacters of the bluetooth message 
.PP
Definition at line \fB35\fP of file \fBslave\&.ino\fP\&.
.SS "double min = 2"
if foward is less then min the car dont move at all 
.PP
Definition at line \fB29\fP of file \fBslave\&.ino\fP\&.
.SS "const int trig = 13"
pin for the trig from the distance sensor 
.PP
Definition at line \fB38\fP of file \fBslave\&.ino\fP\&.
.SS "double turn = 0"
In degrees how much the front of the car have turned 
.PP
Definition at line \fB28\fP of file \fBslave\&.ino\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Mini-Project-FPI from the source code\&.
